mkdir -p .do
cat > .do/app.yaml << 'EOF'
name: tlaix-app
region: nyc

services:
- name: web
  github:
    repo: TU_USUARIO/tlaix
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 60
  envs:
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: REEMPLAZAR_DESPUES
  - key: DB_PORT
    value: "25060"
  - key: DB_DATABASE
    value: defaultdb
  - key: DB_USERNAME
    value: doadmin
  - key: DB_PASSWORD
    value: REEMPLAZAR_DESPUES
    type: SECRET
  - key: CACHE_STORE
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: sync
  - key: APP_KEY
    value: base64:nNfWXmSembBMj41R4+jdQ6xbQD4vr6WRXOsL5vgt1aY=
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
EOF